### ISSUE TITLE
不支持pc客户端吗

### ISSUE THREAD

**Issue by bazhabazha** [JZPPP/MaaBD2#1]
上一版有win32选项时，试了下好像不行。

**Comment by JZPPP** [comment]
棕色尘埃2只能模拟器玩吧？有PC版？

**Comment by JZPPP** [comment]
还没适配，我有空看一下

**Comment by JZPPP** [comment]
看了一下所谓的PC版好像是google player PC上面的，应该不会考虑支持了，可以用模拟器版（
